export const MANGA_DETAILS_LIST_SELECTOR = 'div.manga-info-top'
export const MANGA_TITLE_SELECTOR = 'li:nth-child(1) > h1'
export const MANGA_SUMMARY_SELECTOR = 'div#noidungm'
export const MANGA_ALTERNATIVE_TITLES_SELECTOR = 'li:nth-child(1) > h2'
export const MANGA_AUTHOR_SELECTOR = 'li:nth-child(2) > a'
export const MANGA_STATUS_SELECTOR = 'li:nth-child(3)'
export const MANGA_GENRES_SELECTOR = 'li:nth-child(7) > a'
export const MANGA_UPDATED_AT_SELECTOR = 'li:nth-child(4)'
export const MANGA_VIEWS_SELECTOR = 'li:nth-child(6)'

export const CHAPTERS_SELECTOR = 'div.chapter-list > div.row'
export const CHAPTER_TITLE_SELECTOR = 'span:nth-child(1) > a'
export const CHAPTER_CREATED_AT_SELECTOR = 'span:nth-child(3)'
export const CHAPTER_VIEWS_SELECTOR = 'span:nth-child(2)'
